server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
    
 # dont register this application with eureka as its eurake server, dont fetch its own registry